import { Language, Crop, PreservationAction } from './types';

export const LANGUAGES: { code: Language; label: string }[] = [
  { code: 'en', label: 'English' },
  { code: 'hi', label: 'हिंदी' },
  { code: 'mr', label: 'मराठी' },
];

export const CROPS: Crop[] = [
  // Cereals
  { id: 'rice', name: { en: 'Rice (Paddy)', hi: 'चावल (धान)', mr: 'तांदूळ (धान)' } },
  { id: 'wheat', name: { en: 'Wheat', hi: 'गेहूं', mr: 'गहू' } },
  { id: 'maize', name: { en: 'Maize (Corn)', hi: 'मक्का', mr: 'मका' } },
  { id: 'barley', name: { en: 'Barley', hi: 'जौ', mr: 'जव' } },
  { id: 'ragi', name: { en: 'Ragi (Finger Millet)', hi: 'रागी', mr: 'नाचणी' } },
  { id: 'jowar', name: { en: 'Jowar (Sorghum)', hi: 'ज्वार', mr: 'ज्वारी' } },
  { id: 'bajra', name: { en: 'Bajra (Pearl Millet)', hi: 'बाजरा', mr: 'बाजरी' } },
  { id: 'foxtail_millet', name: { en: 'Foxtail Millet', hi: 'कंगनी', mr: 'राळा' } },
  { id: 'kodo_millet', name: { en: 'Kodo Millet', hi: 'कोदो', mr: 'कोदरा' } },
  { id: 'little_millet', name: { en: 'Little Millet', hi: 'कुटकी', mr: 'वरी' } },
  { id: 'barnyard_millet', name: { en: 'Barnyard Millet', hi: 'सांवा', mr: 'भगर' } },
  { id: 'buckwheat', name: { en: 'Buckwheat', hi: 'कुट्टू', mr: 'कुट्टू' } },
  { id: 'amaranth', name: { en: 'Amaranth', hi: 'राजगिरा', mr: 'राजगिरा' } },
  { id: 'quinoa', name: { en: 'Quinoa', hi: 'क्विनोआ', mr: 'क्विनोआ' } },

  // Pulses
  { id: 'gram', name: { en: 'Chickpea (Gram)', hi: 'चना', mr: 'हरभरा' } },
  { id: 'tur', name: { en: 'Pigeon Pea (Tur/Arhar)', hi: 'अरहर (तुअर)', mr: 'तूर' } },
  { id: 'masoor', name: { en: 'Lentil (Masoor)', hi: 'मसूर', mr: 'मसूर' } },
  { id: 'moong', name: { en: 'Moong (Green Gram)', hi: 'मूंग', mr: 'मूग' } },
  { id: 'urad', name: { en: 'Urad (Black Gram)', hi: 'उड़द', mr: 'उडीद' } },
  { id: 'moth_bean', name: { en: 'Moth Bean', hi: 'मोठ', mr: 'मटकी' } },
  { id: 'horse_gram', name: { en: 'Horse Gram', hi: 'कुलथी', mr: 'हुलगं' } },
  { id: 'cowpea', name: { en: 'Cowpea (Lobia)', hi: 'लोबिया', mr: 'चवळी' } },
  { id: 'field_pea', name: { en: 'Field Pea', hi: 'मटर', mr: 'वाटाणा' } },

  // Fruits
  { id: 'mango', name: { en: 'Mango', hi: 'आम', mr: 'आंबा' } },
  { id: 'banana', name: { en: 'Banana', hi: 'केला', mr: 'केळी' } },
  { id: 'papaya', name: { en: 'Papaya', hi: 'पपीता', mr: 'पपई' } },
  { id: 'pineapple', name: { en: 'Pineapple', hi: 'अनानास', mr: 'अननस' } },
  { id: 'guava', name: { en: 'Guava', hi: 'अमरूद', mr: 'पेरू' } },
  { id: 'jackfruit', name: { en: 'Jackfruit', hi: 'कटहल', mr: 'फणस' } },
  { id: 'custard_apple', name: { en: 'Custard Apple', hi: 'शरीफा', mr: 'सीताफळ' } },
  { id: 'sapota', name: { en: 'Sapota', hi: 'चीकू', mr: 'चिकू' } },
  { id: 'orange', name: { en: 'Orange', hi: 'संतरा', mr: 'संत्रा' } },
  { id: 'lemon', name: { en: 'Lemon', hi: 'नींबू', mr: 'लिंबू' } },
  { id: 'sweet_lime', name: { en: 'Sweet Lime', hi: 'मौसंबी', mr: 'मोसंबी' } },
  { id: 'grapefruit', name: { en: 'Grapefruit', hi: 'चकूतरा', mr: 'ग्रेपफ्रूट' } },
  { id: 'apple', name: { en: 'Apple', hi: 'सेब', mr: 'सफरचंद' } },
  { id: 'pear', name: { en: 'Pear', hi: 'नाशपाती', mr: 'पेअर' } },
  { id: 'plum', name: { en: 'Plum', hi: 'आलू बुखारा', mr: 'प्लम' } },
  { id: 'peach', name: { en: 'Peach', hi: 'आड़ू', mr: 'पीच' } },
  { id: 'cherry', name: { en: 'Cherry', hi: 'चेरी', mr: 'चेरी' } },
  { id: 'walnut', name: { en: 'Walnut', hi: 'अखरोट', mr: 'अक्रोड' } },
  { id: 'almond', name: { en: 'Almond', hi: 'बादाम', mr: 'बादाम' } },
  { id: 'grapes', name: { en: 'Grapes', hi: 'अंगूर', mr: 'द्राक्षे' } },
  { id: 'strawberry', name: { en: 'Strawberry', hi: 'स्ट्रॉबेरी', mr: 'स्ट्रॉबेरी' } },
  { id: 'mulberry', name: { en: 'Mulberry', hi: 'शहतूत', mr: 'तुती' } },
  { id: 'raspberry', name: { en: 'Raspberry', hi: 'रसभरी', mr: 'रास्पबेरी' } },
  { id: 'blueberry', name: { en: 'Blueberry', hi: 'ब्लूबेरी', mr: 'ब्लूबेरी' } },
  { id: 'cashew', name: { en: 'Cashew', hi: 'काजू', mr: 'काजू' } },
  { id: 'coconut', name: { en: 'Coconut', hi: 'नारियल', mr: 'नारळ' } },
  { id: 'date_palm', name: { en: 'Date Palm', hi: 'खजूर', mr: 'खजूर' } },
  { id: 'pistachio', name: { en: 'Pistachio', hi: 'पिस्ता', mr: 'पिस्ता' } },
  { id: 'betel_nut', name: { en: 'Betel Nut', hi: 'सुपारी', mr: 'सुपारी' } },
  { id: 'kiwi', name: { en: 'Kiwi', hi: 'कीवी', mr: 'किवी' } },
  { id: 'dragon_fruit', name: { en: 'Dragon Fruit', hi: 'ड्रैगन फ्रूट', mr: 'ड्रॅगन फ्रूट' } },
  { id: 'avocado', name: { en: 'Avocado', hi: 'एवोकैडो', mr: 'एवोकॅडो' } },
  { id: 'fig', name: { en: 'Fig', hi: 'अंजीर', mr: 'अंजीर' } },
  { id: 'passion_fruit', name: { en: 'Passion Fruit', hi: 'पैशन फ्रूट', mr: 'पॅशन फ्रूट' } },

  // Vegetables
  { id: 'potato', name: { en: 'Potato', hi: 'आलू', mr: 'बटाटा' } },
  { id: 'tomato', name: { en: 'Tomato', hi: 'टमाटर', mr: 'टोमॅटो' } },
  { id: 'onion', name: { en: 'Onion', hi: 'प्याज', mr: 'कांदा' } },
  { id: 'cabbage', name: { en: 'Cabbage', hi: 'पत्ता गोभी', mr: 'कोबी' } },
  { id: 'cauliflower', name: { en: 'Cauliflower', hi: 'फूल गोभी', mr: 'फ्लॉवर' } },
  { id: 'brinjal', name: { en: 'Brinjal', hi: 'बैंगन', mr: 'वांगे' } },
  { id: 'pumpkin', name: { en: 'Pumpkin', hi: 'कद्दू', mr: 'भोपळा' } },
  { id: 'cucumber', name: { en: 'Cucumber', hi: 'खीरा', mr: 'काकडी' } },
  { id: 'bitter_gourd', name: { en: 'Bitter Gourd', hi: 'करेला', mr: 'कारले' } },
  { id: 'leafy_vegetables', name: { en: 'Leafy Vegetables', hi: 'पत्तेदार सब्जियां', mr: 'पालेभाज्या' } },

  // Oilseeds
  { id: 'groundnut', name: { en: 'Groundnut', hi: 'मूंगफली', mr: 'भुईमूग' } },
  { id: 'mustard', name: { en: 'Mustard/Rapeseed', hi: 'सरसों', mr: 'मोहरी' } },
  { id: 'soybean', name: { en: 'Soybean', hi: 'सोयाबीन', mr: 'सोयाबीन' } },
  { id: 'sunflower', name: { en: 'Sunflower', hi: 'सूरजमुखी', mr: 'सूर्यफूल' } },
  { id: 'sesame', name: { en: 'Sesame (Til)', hi: 'तिल', mr: 'तीळ' } },
  { id: 'safflower', name: { en: 'Safflower', hi: 'कुसुम', mr: 'करडई' } },
  { id: 'linseed', name: { en: 'Linseed', hi: 'अलसी', mr: 'जवस' } },
  { id: 'castor', name: { en: 'Castor', hi: 'अरंडी', mr: 'एरंडी' } },
  { id: 'niger', name: { en: 'Niger', hi: 'रामतिल', mr: 'कारळे' } },
  { id: 'oil_palm', name: { en: 'Oil Palm', hi: 'पाम तेल', mr: 'पाम तेल' } },

  // Fiber Crops
  { id: 'cotton', name: { en: 'Cotton', hi: 'कपास', mr: 'कापूस' } },
  { id: 'jute', name: { en: 'Jute', hi: 'जूट', mr: 'ताग' } },
  { id: 'flax', name: { en: 'Flax', hi: 'सन', mr: 'अंबाडी' } },
  { id: 'hemp', name: { en: 'Hemp', hi: 'भांग', mr: 'गांजा' } },
  { id: 'coir', name: { en: 'Coir', hi: 'नारियल रेशा', mr: 'नारळ काथ्या' } },
  { id: 'sunhemp', name: { en: 'Sunhemp', hi: 'सनहेम्प', mr: 'ताग' } },
  { id: 'ramie', name: { en: 'Ramie', hi: 'रेमी', mr: 'रेमी' } },
  { id: 'sisal', name: { en: 'Sisal', hi: 'सिसाल', mr: 'सिसाल' } },

  // Plantation Crops
  { id: 'tea', name: { en: 'Tea', hi: 'चाय', mr: 'चहा' } },
  { id: 'coffee', name: { en: 'Coffee', hi: 'कॉफी', mr: 'कॉफी' } },
  { id: 'rubber', name: { en: 'Rubber', hi: 'रबड़', mr: 'रबर' } },
  { id: 'arecanut', name: { en: 'Arecanut', hi: 'सुपारी', mr: 'सुपारी' } },
  { id: 'cocoa', name: { en: 'Cocoa', hi: 'कोको', mr: 'कोको' } },

  // Cash Crops & Spices
  { id: 'sugarcane', name: { en: 'Sugarcane', hi: 'गन्ना', mr: 'ऊस' } },
  { id: 'tobacco', name: { en: 'Tobacco', hi: 'तंबाकू', mr: 'तंबाखू' } },
  { id: 'turmeric', name: { en: 'Turmeric', hi: 'हल्दी', mr: 'हळद' } },
  { id: 'ginger', name: { en: 'Ginger', hi: 'अदरक', mr: 'आले' } },
  { id: 'black_pepper', name: { en: 'Black Pepper', hi: 'काली मिर्च', mr: 'काळी मिरी' } },
  { id: 'cardamom', name: { en: 'Cardamom', hi: 'इलायची', mr: 'वेलची' } },
  { id: 'clove', name: { en: 'Clove', hi: 'लौंग', mr: 'लवंग' } },
  { id: 'nutmeg', name: { en: 'Nutmeg', hi: 'जायफल', mr: 'जायफळ' } },
  { id: 'cinnamon', name: { en: 'Cinnamon', hi: 'दालचीनी', mr: 'दालचिनी' } },
  { id: 'vanilla', name: { en: 'Vanilla', hi: 'वैनिला', mr: 'व्हॅनिला' } },
  { id: 'chilli', name: { en: 'Chilies', hi: 'मिर्च', mr: 'मिरची' } },

  // Medicinal & Aromatic Plants
  { id: 'ashwagandha', name: { en: 'Ashwagandha', hi: 'अश्वगंधा', mr: 'अश्वगंधा' } },
  { id: 'tulsi', name: { en: 'Tulsi', hi: 'तुलसी', mr: 'तुळस' } },
  { id: 'aloe_vera', name: { en: 'Aloe Vera', hi: 'घृतकुमारी', mr: 'कोरफड' } },
  { id: 'neem', name: { en: 'Neem', hi: 'नीम', mr: 'कडुनिंब' } },
  { id: 'brahmi', name: { en: 'Brahmi', hi: 'ब्राह्मी', mr: 'ब्राह्मी' } },
  { id: 'shatavari', name: { en: 'Shatavari', hi: 'शतावरी', mr: 'शतावरी' } },
  { id: 'giloy', name: { en: 'Giloy', hi: 'गिलोय', mr: 'गुळवेल' } },
  { id: 'arjuna', name: { en: 'Arjuna', hi: 'अर्जुन', mr: 'अर्जुन' } },
  { id: 'isabgol', name: { en: 'Isabgol', hi: 'इसबगोल', mr: 'इसबगोल' } },
  { id: 'safed_musli', name: { en: 'Safed Musli', hi: 'सफेद मूसली', mr: 'सफेद मुसळी' } },
  { id: 'sarpagandha', name: { en: 'Sarpagandha', hi: 'सर्पगंधा', mr: 'सर्पगंधा' } },
  { id: 'amla', name: { en: 'Amla', hi: 'आंवला', mr: 'आवळा' } },
];

export const STATES_DISTRICTS: { [state: string]: string[] } = {
  'Andhra Pradesh': ['Anantapur', 'Chittoor', 'East Godavari', 'Guntur', 'Krishna', 'Kurnool', 'Prakasam', 'Srikakulam', 'Visakhapatnam', 'Vizianagaram', 'West Godavari', 'Kadapa', 'Nellore'],
  'Arunachal Pradesh': ['Tawang', 'West Kameng', 'East Kameng', 'Papum Pare', 'Kurung Kumey', 'Kra Daadi', 'Lower Subansiri', 'Upper Subansiri', 'West Siang', 'East Siang', 'Siang', 'Upper Siang', 'Lower Siang', 'Lower Dibang Valley', 'Upper Dibang Valley', 'Anjaw', 'Lohit', 'Namsai', 'Changlang', 'Tirap', 'Longding'],
  'Assam': ['Baksa', 'Barpeta', 'Biswanath', 'Bongaigaon', 'Cachar', 'Charaideo', 'Chirang', 'Darrang', 'Dhemaji', 'Dhubri', 'Dibrugarh', 'Goalpara', 'Golaghat', 'Hailakandi', 'Hojai', 'Jorhat', 'Kamrup Metropolitan', 'Kamrup', 'Karbi Anglong', 'Karimganj', 'Kokrajhar', 'Lakhimpur', 'Majuli', 'Morigaon', 'Nagaon', 'Nalbari', 'Dima Hasao', 'Sivasagar', 'Sonitpur', 'South Salmara-Mankachar', 'Tinsukia', 'Udalguri', 'West Karbi Anglong'],
  'Bihar': ['Araria', 'Arwal', 'Aurangabad', 'Banka', 'Begusarai', 'Bhagalpur', 'Bhojpur', 'Buxar', 'Darbhanga', 'East Champaran', 'Gaya', 'Gopalganj', 'Jamui', 'Jehanabad', 'Kaimur', 'Katihar', 'Khagaria', 'Kishanganj', 'Lakhisarai', 'Madhepura', 'Madhubani', 'Munger', 'Muzaffarpur', 'Nalanda', 'Nawada', 'Patna', 'Purnia', 'Rohtas', 'Saharsa', 'Samastipur', 'Saran', 'Sheikhpura', 'Sheohar', 'Sitamarhi', 'Siwan', 'Supaul', 'Vaishali', 'West Champaran'],
  'Chhattisgarh': ['Balod', 'Baloda Bazar', 'Balrampur', 'Bastar', 'Bemetara', 'Bijapur', 'Bilaspur', 'Dantewada', 'Dhamtari', 'Durg', 'Gariaband', 'Janjgir-Champa', 'Jashpur', 'Kabirdham', 'Kanker', 'Kondagaon', 'Korba', 'Koriya', 'Mahasamund', 'Mungeli', 'Narayanpur', 'Raigarh', 'Raipur', 'Rajnandgaon', 'Sukma', 'Surajpur', 'Surguja'],
  'Goa': ['North Goa', 'South Goa'],
  'Gujarat': ['Ahmedabad', 'Amreli', 'Anand', 'Aravalli', 'Banaskantha', 'Bharuch', 'Bhavnagar', 'Botad', 'Chhota Udepur', 'Dahod', 'Dang', 'Devbhoomi Dwarka', 'Gandhinagar', 'Gir Somnath', 'Jamnagar', 'Junagadh', 'Kheda', 'Kutch', 'Mahisagar', 'Mehsana', 'Morbi', 'Narmada', 'Navsari', 'Panchmahal', 'Patan', 'Porbandar', 'Rajkot', 'Sabarkantha', 'Surat', 'Surendranagar', 'Tapi', 'Vadodara', 'Valsad'],
  'Haryana': ['Ambala', 'Bhiwani', 'Charkhi Dadri', 'Faridabad', 'Fatehabad', 'Gurugram', 'Hisar', 'Jhajjar', 'Jind', 'Kaithal', 'Karnal', 'Kurukshetra', 'Mahendragarh', 'Nuh', 'Palwal', 'Panchkula', 'Panipat', 'Rewari', 'Rohtak', 'Sirsa', 'Sonipat', 'Yamunanagar'],
  'Himachal Pradesh': ['Bilaspur', 'Chamba', 'Hamirpur', 'Kangra', 'Kinnaur', 'Kullu', 'Lahaul and Spiti', 'Mandi', 'Shimla', 'Sirmaur', 'Solan', 'Una'],
  'Jharkhand': ['Bokaro', 'Chatra', 'Deoghar', 'Dhanbad', 'Dumka', 'East Singhbhum', 'Garhwa', 'Giridih', 'Godda', 'Gumla', 'Hazaribagh', 'Jamtara', 'Khunti', 'Koderma', 'Latehar', 'Lohardaga', 'Pakur', 'Palamu', 'Ramgarh', 'Ranchi', 'Sahibganj', 'Seraikela Kharsawan', 'Simdega', 'West Singhbhum'],
  'Karnataka': ['Bagalkot', 'Ballari', 'Belagavi', 'Bengaluru Rural', 'Bengaluru Urban', 'Bidar', 'Chamarajanagar', 'Chikkaballapur', 'Chikkamagaluru', 'Chitradurga', 'Dakshina Kannada', 'Davanagere', 'Dharwad', 'Gadag', 'Hassan', 'Haveri', 'Kalaburagi', 'Kodagu', 'Kolar', 'Koppal', 'Mandya', 'Mysuru', 'Raichur', 'Ramanagara', 'Shivamogga', 'Tumakuru', 'Udupi', 'Uttara Kannada', 'Vijayapura', 'Yadgir'],
  'Kerala': ['Alappuzha', 'Ernakulam', 'Idukki', 'Kannur', 'Kasaragod', 'Kollam', 'Kottayam', 'Kozhikode', 'Malappuram', 'Palakkad', 'Pathanamthitta', 'Thiruvananthapuram', 'Thrissur', 'Wayanad'],
  'Madhya Pradesh': ['Agar Malwa', 'Alirajpur', 'Anuppur', 'Ashoknagar', 'Balaghat', 'Barwani', 'Betul', 'Bhind', 'Bhopal', 'Burhanpur', 'Chhatarpur', 'Chhindwara', 'Damoh', 'Datia', 'Dewas', 'Dhar', 'Dindori', 'Guna', 'Gwalior', 'Harda', 'Hoshangabad', 'Indore', 'Jabalpur', 'Jhabua', 'Katni', 'Khandwa', 'Khargone', 'Mandla', 'Mandsaur', 'Morena', 'Narsinghpur', 'Neemuch', 'Panna', 'Raisen', 'Rajgarh', 'Ratlam', 'Rewa', 'Sagar', 'Satna', 'Sehore', 'Seoni', 'Shahdol', 'Shajapur', 'Sheopur', 'Shivpuri', 'Sidhi', 'Singrauli', 'Tikamgarh', 'Ujjain', 'Umaria', 'Vidisha'],
  'Maharashtra': ['Ahmednagar', 'Akola', 'Amravati', 'Aurangabad', 'Beed', 'Bhandara', 'Buldhana', 'Chandrapur', 'Dhule', 'Gadchiroli', 'Gondia', 'Hingoli', 'Jalgaon', 'Jalna', 'Kolhapur', 'Latur', 'Mumbai City', 'Mumbai Suburban', 'Nagpur', 'Nanded', 'Nandurbar', 'Nashik', 'Osmanabad', 'Palghar', 'Parbhani', 'Pune', 'Raigad', 'Ratnagiri', 'Sangli', 'Satara', 'Sindhudurg', 'Solapur', 'Thane', 'Wardha', 'Washim', 'Yavatmal'],
  'Manipur': ['Bishnupur', 'Chandel', 'Churachandpur', 'Imphal East', 'Imphal West', 'Jiribam', 'Kakching', 'Kamjong', 'Kangpokpi', 'Noney', 'Pherzawl', 'Senapati', 'Tamenglong', 'Tengnoupal', 'Thoubal', 'Ukhrul'],
  'Meghalaya': ['East Garo Hills', 'East Jaintia Hills', 'East Khasi Hills', 'North Garo Hills', 'Ri Bhoi', 'South Garo Hills', 'South West Garo Hills', 'South West Khasi Hills', 'West Garo Hills', 'West Jaintia Hills', 'West Khasi Hills'],
  'Mizoram': ['Aizawl', 'Champhai', 'Kolasib', 'Lawngtlai', 'Lunglei', 'Mamit', 'Saiha', 'Serchhip'],
  'Nagaland': ['Dimapur', 'Kiphire', 'Kohima', 'Longleng', 'Mokokchung', 'Mon', 'Peren', 'Phek', 'Tuensang', 'Wokha', 'Zunheboto'],
  'Odisha': ['Angul', 'Balangir', 'Balasore', 'Bargarh', 'Bhadrak', 'Boudh', 'Cuttack', 'Deogarh', 'Dhenkanal', 'Gajapati', 'Ganjam', 'Jagatsinghpur', 'Jajpur', 'Jharsuguda', 'Kalahandi', 'Kandhamal', 'Kendrapara', 'Kendujhar', 'Khordha', 'Koraput', 'Malkangiri', 'Mayurbhanj', 'Nabarangpur', 'Nayagarh', 'Nuapada', 'Puri', 'Rayagada', 'Sambalpur', 'Sonepur', 'Sundargarh'],
  'Punjab': ['Amritsar', 'Barnala', 'Bathinda', 'Faridkot', 'Fatehgarh Sahib', 'Fazilka', 'Ferozepur', 'Gurdaspur', 'Hoshiarpur', 'Jalandhar', 'Kapurthala', 'Ludhiana', 'Mansa', 'Moga', 'Muktsar', 'Pathankot', 'Patiala', 'Rupnagar', 'Sahibzada Ajit Singh Nagar', 'Sangrur', 'Shahid Bhagat Singh Nagar', 'Sri Muktsar Sahib', 'Tarn Taran'],
  'Rajasthan': ['Ajmer', 'Alwar', 'Banswara', 'Baran', 'Barmer', 'Bharatpur', 'Bhilwara', 'Bikaner', 'Bundi', 'Chittorgarh', 'Churu', 'Dausa', 'Dholpur', 'Dungarpur', 'Hanumangarh', 'Jaipur', 'Jaisalmer', 'Jalore', 'Jhalawar', 'Jhunjhunu', 'Jodhpur', 'Karauli', 'Kota', 'Nagaur', 'Pali', 'Pratapgarh', 'Rajsamand', 'Sawai Madhopur', 'Sikar', 'Sirohi', 'Sri Ganganagar', 'Tonk', 'Udaipur'],
  'Sikkim': ['East Sikkim', 'North Sikkim', 'South Sikkim', 'West Sikkim'],
  'Tamil Nadu': ['Ariyalur', 'Chengalpattu', 'Chennai', 'Coimbatore', 'Cuddalore', 'Dharmapuri', 'Dindigul', 'Erode', 'Kallakurichi', 'Kanchipuram', 'Kanyakumari', 'Karur', 'Krishnagiri', 'Madurai', 'Mayiladuthurai', 'Nagapattinam', 'Namakkal', 'Nilgiris', 'Perambalur', 'Pudukkottai', 'Ramanathapuram', 'Ranipet', 'Salem', 'Sivaganga', 'Tenkasi', 'Thanjavur', 'Theni', 'Thoothukudi', 'Tiruchirappalli', 'Tirunelveli', 'Tirupathur', 'Tiruppur', 'Tiruvallur', 'Tiruvannamalai', 'Tiruvarur', 'Vellore', 'Viluppuram', 'Virudhunagar'],
  'Telangana': ['Adilabad', 'Bhadradri Kothagudem', 'Hyderabad', 'Jagtial', 'Jangaon', 'Jayashankar Bhupalpally', 'Jogulamba Gadwal', 'Kamareddy', 'Karimnagar', 'Khammam', 'Kumuram Bheem Asifabad', 'Mahabubabad', 'Mahabubnagar', 'Mancherial', 'Medak', 'Medchal-Malkajgiri', 'Mulugu', 'Nagarkurnool', 'Nalgonda', 'Narayanpet', 'Nirmal', 'Nizamabad', 'Peddapalli', 'Rajanna Sircilla', 'Rangareddy', 'Sangareddy', 'Siddipet', 'Suryapet', 'Vikarabad', 'Wanaparthy', 'Warangal Rural', 'Warangal Urban', 'Yadadri Bhuvanagiri'],
  'Tripura': ['Dhalai', 'Gomati', 'Khowai', 'North Tripura', 'Sepahijala', 'South Tripura', 'Unakoti', 'West Tripura'],
  'Uttar Pradesh': ['Agra', 'Aligarh', 'Allahabad', 'Ambedkar Nagar', 'Amethi', 'Amroha', 'Auraiya', 'Azamgarh', 'Baghpat', 'Bahraich', 'Ballia', 'Balrampur', 'Banda', 'Barabanki', 'Bareilly', 'Basti', 'Bhadohi', 'Bijnor', 'Budaun', 'Bulandshahr', 'Chandauli', 'Chitrakoot', 'Deoria', 'Etah', 'Etawah', 'Faizabad', 'Farrukhabad', 'Fatehpur', 'Firozabad', 'Gautam Buddha Nagar', 'Ghaziabad', 'Ghazipur', 'Gonda', 'Gorakhpur', 'Hamirpur', 'Hapur', 'Hardoi', 'Hathras', 'Jalaun', 'Jaunpur', 'Jhansi', 'Kannauj', 'Kanpur Dehat', 'Kanpur Nagar', 'Kasganj', 'Kaushambi', 'Kheri', 'Kushinagar', 'Lalitpur', 'Lucknow', 'Maharajganj', 'Mahoba', 'Mainpuri', 'Mathura', 'Mau', 'Meerut', 'Mirzapur', 'Moradabad', 'Muzaffarnagar', 'Pilibhit', 'Pratapgarh', 'Raebareli', 'Rampur', 'Saharanpur', 'Sambhal', 'Sant Kabir Nagar', 'Shahjahanpur', 'Shamli', 'Shravasti', 'Siddharthnagar', 'Sitapur', 'Sonbhadra', 'Sultanpur', 'Unnao', 'Varanasi'],
  'Uttarakhand': ['Almora', 'Bageshwar', 'Chamoli', 'Champawat', 'Dehradun', 'Haridwar', 'Nainital', 'Pauri Garhwal', 'Pithoragarh', 'Rudraprayag', 'Tehri Garhwal', 'Udham Singh Nagar', 'Uttarkashi'],
  'West Bengal': ['Alipurduar', 'Bankura', 'Birbhum', 'Cooch Behar', 'Dakshin Dinajpur', 'Darjeeling', 'Hooghly', 'Howrah', 'Jalpaiguri', 'Jhargram', 'Kalimpong', 'Kolkata', 'Malda', 'Murshidabad', 'Nadia', 'North 24 Parganas', 'Paschim Bardhaman', 'Paschim Medinipur', 'Purba Bardhaman', 'Purba Medinipur', 'Purulia', 'South 24 Parganas', 'Uttar Dinajpur'],
  'Andaman and Nicobar Islands': ['Nicobar', 'North and Middle Andaman', 'South Andaman'],
  'Chandigarh': ['Chandigarh'],
  'Dadra and Nagar Haveli and Daman and Diu': ['Dadra and Nagar Haveli', 'Daman', 'Diu'],
  'Lakshadweep': ['Lakshadweep'],
  'Delhi': ['Central Delhi', 'East Delhi', 'New Delhi', 'North Delhi', 'North East Delhi', 'North West Delhi', 'Shahdara', 'South Delhi', 'South East Delhi', 'South West Delhi', 'West Delhi'],
  'Puducherry': ['Karaikal', 'Mahe', 'Puducherry', 'Yanam'],
  'Ladakh': ['Kargil', 'Leh'],
  'Jammu and Kashmir': ['Anantnag', 'Bandipora', 'Baramulla', 'Budgam', 'Doda', 'Ganderbal', 'Jammu', 'Kathua', 'Kishtwar', 'Kulgam', 'Kupwara', 'Poonch', 'Pulwama', 'Rajouri', 'Ramban', 'Reasi', 'Samba', 'Shopian', 'Srinagar', 'Udhampur'],
};

export const PRESERVATION_ACTIONS: PreservationAction[] = [
  {
    name: { en: 'Warehouse + Ventilation', hi: 'गोदाम + वेंटिलेशन', mr: 'गोदाम + वेंटिलेशन' },
    cost: 5000,
    effectiveness: 92,
  },
  {
    name: { en: 'Cold Storage', hi: 'कोल्ड स्टोरेज', mr: 'कोल्ड स्टोरेज' },
    cost: 12000,
    effectiveness: 98,
  },
  {
    name: { en: 'Wax Coating', hi: 'वैक्स कोटिंग', mr: 'वॅक्स कोटिंग' },
    cost: 2000,
    effectiveness: 75,
  },
];

export const TRANSLATIONS = {
  en: {
    heroTitle: "Save 40% Earnings! Right Time, Right Market",
    heroSub: "AI-powered harvest and market intelligence for Indian farmers.",
    village: "Village",
    district: "District",
    state: "State",
    cropName: "Crop Name",
    yield: "Expected Yield (Quintals)",
    getInfo: "Get Information",
    harvestWindow: "Optimal Harvest Window",
    bestMarkets: "Top 5 Mandis for Your Crop",
    mandi: "Mandi",
    price: "Today's Price",
    distance: "Distance",
    profit: "Total Profit",
    storageRisk: "Storage Spoilage Risk",
    preservation: "Preservation Actions",
    cost: "Cost",
    effective: "Effective",
    riskMeter: "Risk Meter",
    days: "days",
    why: "Why",
    back: "Back",
    share: "Share on WhatsApp",
    voice: "Voice Input",
    liveMandi: "Live Mandi Comparison",
    trend: "7-Day Trend",
    weatherForecast: "5-Day Weather Forecast",
    temp: "Temp",
    condition: "Condition",
    advice: "Advice",
    marketWatch: "Market Watch",
    quintal: "quintal",
    suggestions: "Top Suggestions",
    topSuggestions: "3 Best Suggestions (Price + Distance)",
    source: "Source",
    accuracy: "Accuracy",
    lastUpdated: "Last Updated",
  },
  hi: {
    heroTitle: "40% कमाई बचाओ! सही समय, सही मंडी",
    heroSub: "भारतीय किसानों के लिए AI-आधारित फसल और बाजार की जानकारी।",
    village: "गांव",
    district: "जिला",
    state: "राज्य",
    cropName: "फसल का नाम",
    yield: "अपेक्षित उपज (क्विंटल में)",
    getInfo: "जानकारी लो",
    harvestWindow: "फसल काटने का सबसे अच्छा समय",
    bestMarkets: "आपकी फसल के लिए TOP 5 मंडियां",
    mandi: "मंडी",
    price: "आज का भाव",
    distance: "दूरी",
    profit: "कुल मुनाफा",
    storageRisk: "भंडारण में खराब होने का खतरा",
    preservation: "संरक्षण के उपाय",
    cost: "लागत",
    effective: "प्रभावशीलता",
    riskMeter: "जोखिम मीटर",
    days: "दिन",
    why: "कारण",
    back: "पीछे",
    share: "WhatsApp पर साझा करें",
    voice: "आवाज इनपुट",
    liveMandi: "लाइव मंडी तुलना",
    trend: "7-दिन का रुझान",
    weatherForecast: "5-दिन का मौसम पूर्वानुमान",
    temp: "तापमान",
    condition: "स्थिति",
    advice: "सलाह",
    marketWatch: "बाजार भाव",
    quintal: "क्विंटल",
    suggestions: "शीर्ष सुझाव",
    topSuggestions: "3 सर्वश्रेष्ठ सुझाव (कीमत + दूरी)",
    source: "स्रोत",
    accuracy: "सटीकता",
    lastUpdated: "अंतिम अपडेट",
  },
  mr: {
    heroTitle: "४०% कमाई वाचवा! योग्य वेळ, योग्य मंडी",
    heroSub: "भारतीय शेतकऱ्यांसाठी AI-आधारित कापणी आणि बाजार माहिती.",
    village: "गाव",
    district: "जिल्हा",
    state: "राज्य",
    cropName: "पिकाचे नाव",
    yield: "अपेक्षित उत्पन्न (क्विंटलमध्ये)",
    getInfo: "माहिती मिळवा",
    harvestWindow: "पीक कापणीची सर्वोत्तम वेळ",
    bestMarkets: "तुमच्या पिकासाठी TOP 5 मंडई",
    mandi: "मंडई",
    price: "आजचा भाव",
    distance: "अंतर",
    profit: "एकूण नफा",
    storageRisk: "साठवणुकीत खराब होण्याचा धोका",
    preservation: "संरक्षण उपाय",
    cost: "खर्च",
    effective: "प्रभावी",
    riskMeter: "धोका मीटर",
    days: "दिवस",
    why: "कारण",
    back: "मागे",
    share: "WhatsApp वर शेअर करा",
    voice: "आवाज इनपुट",
    liveMandi: "लाईव्ह मंडई तुलना",
    trend: "७-दिवसांचा कल",
    weatherForecast: "५-दिवसांचा हवामान अंदाज",
    temp: "तापमान",
    condition: "स्थिती",
    advice: "सल्ला",
    marketWatch: "बाजार भाव",
    quintal: "क्विंटल",
    suggestions: "प्रमुख शिफारसी",
    topSuggestions: "३ सर्वोत्तम शिफारसी (किंमत + अंतर)",
    source: "स्रोत",
    accuracy: "अचूकता",
    lastUpdated: "शेवटचे अपडेट",
  }
};
